# Generated by Django 5.2.4 on 2025-07-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultation",
            name="constants",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="height",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="weight",
        ),
        migrations.AddField(
            model_name="consultation",
            name="heart_rate",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="oxygen_saturation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="tension",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="antecedents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Constant",
        ),
    ]
