# Generated by Django 5.2.4 on 2025-07-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_consultation_constants_remove_patient_age_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="antecedents",
            new_name="diseases",
        ),
        migrations.AddField(
            model_name="patient",
            name="actual_medecines",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="surgeries",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="vaccines",
            field=models.TextField(blank=True, null=True),
        ),
    ]
