# Generated by Django 5.2.4 on 2025-07-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_consultation_is_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="gemini_recommendations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
