# Generated by Django 5.2.4 on 2025-07-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_iaperformancemetrics_prescriptionfeedback_and_more"),
    ]

    operations = []
