# Generated by Django 5.2.4 on 2025-07-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_add_ai_feedback_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('frequent_modification', 'Modification Fréquente'), ('frequent_rejection', 'Rejet Fréquent'), ('good_practice', 'Bonne Pratique'), ('dosage_preference', 'Préférence de Dosage'), ('diagnostic_error', 'Erreur de Diagnostic'), ('prescription_error', 'Erreur de Prescription')], max_length=50)),
                ('description', models.TextField(help_text='Description du pattern identifié')),
                ('frequency', models.PositiveIntegerField(default=1, help_text="Nombre d'occurrences")),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Score de confiance du pattern (0.0 à 1.0)', max_digits=3)),
                ('first_occurrence', models.DateTimeField(auto_now_add=True)),
                ('last_occurrence', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Pattern actif pour enrichissement prompt')),
                ('related_feedbacks', models.ManyToManyField(blank=True, help_text='Feedbacks sources de ce pattern', to='app.prescriptionfeedback')),
            ],
            options={
                'verbose_name': 'Pattern de Feedback',
                'verbose_name_plural': 'Patterns de Feedback',
                'ordering': ['-frequency', '-confidence_score', '-last_occurrence'],
                'unique_together': {('pattern_type', 'description')},
            },
        ),
    ]
